spring:
  application:
    name: SpringBoot-ElasticSearch
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql:///db7?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
  data:
    elasticsearch:
      client:
        reactive:
          endpoints: 127.0.0.1:9200
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

# jpa配置

minio:
  endpoint: http://127.0.0.1:9000
  accessKey: 3x2K4oPLqIzvrEL6w2ya
  secretKey: xPx2PYoNbbxRmEYXgJVUmsPr5zf8OycyiJQJWzKl

